DELETE FROM CITY;
ALTER TABLE CITY AUTO_INCREMENT = 1;
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('San Francisco', 'CA', 'US');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('Chennai', 'TA', 'India');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('Madurai', 'TA', 'India');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('Bengalore', 'KA', 'India');
